# Generated by Django 3.2.4 on 2021-06-14 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=20000)),
                ('price', models.IntegerField()),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=400)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_posted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
